// <auto-generated />
using System;
using AutoBotCleanArchitecture.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoBotCleanArchitecture.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.BotSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("botSignals");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.BotTrading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommandNumber")
                        .HasColumnType("integer");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision");

                    b.Property<string>("NameBot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalProfit")
                        .HasColumnType("double precision");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("botTradings");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdminSender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TypeMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("chatMessages");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chatRooms");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ConfirmEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiredtime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("confirmEmails");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAvatar")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("contents");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.LogHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsSL")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberContract")
                        .HasColumnType("integer");

                    b.Property<double>("PriceBuy")
                        .HasColumnType("double precision");

                    b.Property<double>("Profit")
                        .HasColumnType("double precision");

                    b.Property<double>("ProfitPointTP")
                        .HasColumnType("double precision");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("logHistories");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.OtherContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("otherContents");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("BotTradingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotTradingId");

                    b.HasIndex("UserId");

                    b.ToTable("paymentOrders");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PriceBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotTradingId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionBot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BotTradingId");

                    b.HasIndex("Month", "BotTradingId")
                        .IsUnique();

                    b.ToTable("priceBots");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ProfitLoss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("profitLosses");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PurchaseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BotTradingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PriceBot")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotTradingId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("purchaseHistories");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Exprited")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f08f62-b9b2-4d14-b8e7-3f3d5b0c7a6c"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d1d08c62-c6e2-4d12-b8e8-3f3d5b0c7a6d"),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LockoutEnable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LockoutEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("TwoStep")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b26185e-e90d-4ea6-bea8-5562ad4f627c"),
                            AccessFailedCount = 0,
                            BirthDay = new DateOnly(2000, 1, 1),
                            CreatedDate = new DateTime(2026, 1, 7, 8, 14, 1, 592, DateTimeKind.Utc).AddTicks(8654),
                            Email = "huynhnguyen13122005@gmail.com",
                            FullName = "Quản Trị Viên",
                            IsActive = true,
                            LockoutEnable = false,
                            LockoutEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassWord = "$2a$11$HQe0hJnHsGz3dabdY6FUw.uMrfNVK/w11bVywJ2A3H39tkYPbm80a",
                            PhoneNumber = "0123456789",
                            RoleId = new Guid("c3f08f62-b9b2-4d14-b8e7-3f3d5b0c7a6c"),
                            TwoStep = true,
                            UrlAvatar = "https://res.cloudinary.com/drpxjqd47/image/upload/v1763051875/xusxceivnufh4ncc8peb.jpg",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.UserBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotTradingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotTradingId");

                    b.HasIndex("UserId");

                    b.ToTable("userBots");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Fingerprint")
                        .IsUnique();

                    b.ToTable("userDevices");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletPin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("walletTransactions");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.WithdrawMoney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BankAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserBankName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("withdrawMoneys");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ChatRoom", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("ChatRooms")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ConfirmEmail", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("ConfirmEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.LogHistory", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("LogHistorys")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.BotTrading", "BotTrading")
                        .WithMany()
                        .HasForeignKey("BotTradingId");

                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotTrading");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PriceBot", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.BotTrading", "BotTrading")
                        .WithMany("PriceBots")
                        .HasForeignKey("BotTradingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotTrading");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ProfitLoss", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("ProfitLoss")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.PurchaseHistory", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.BotTrading", "BotTrading")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("BotTradingId");

                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.Wallet", "Wallet")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("WalletId");

                    b.Navigation("BotTrading");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.User", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.UserBot", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.BotTrading", "BotTrading")
                        .WithMany("UsersBots")
                        .HasForeignKey("BotTradingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("UserBots")
                        .HasForeignKey("UserId");

                    b.Navigation("BotTrading");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("AutoBotCleanArchitecture.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.WithdrawMoney", b =>
                {
                    b.HasOne("AutoBotCleanArchitecture.Domain.Entities.User", "User")
                        .WithMany("WithdrawMoneys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.BotTrading", b =>
                {
                    b.Navigation("PriceBots");

                    b.Navigation("PurchaseHistories");

                    b.Navigation("UsersBots");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatRooms");

                    b.Navigation("ConfirmEmails");

                    b.Navigation("LogHistorys");

                    b.Navigation("PaymentOrders");

                    b.Navigation("ProfitLoss");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserBots");

                    b.Navigation("Wallet");

                    b.Navigation("WithdrawMoneys");
                });

            modelBuilder.Entity("AutoBotCleanArchitecture.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("PurchaseHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
